steps:
  - id: get-kube-config
    dir: .
    name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_CORE_PROJECT=$PROJECT_ID
      - CLOUDSDK_COMPUTE_REGION=${_REGION}
      - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
      - KUBECONFIG=/workspace/.kube/config
    args:
      - cluster-info

  - id: deploy
    dir: .
    name: cloudnatived/helm-cloudbuilder
    env:
      - KUBECONFIG=/workspace/.kube/config
    args:
      - helm
      - upgrade
      - --install
      - --create-namespace
      - ${TAG_NAME}-category
      - --namespace=${TAG_NAME}-category
      - --values
      - category/${TAG_NAME}-values.yaml
      - --set
      - container.image=${_REGION}-docker.pkg.dev/$PROJECT_ID/ajustadoati-repo/category
      - --set
      - container.tag=${COMMIT_SHA}
      - ./category
