steps:
  # build only the first stage, so we can run tests with it
  - id: build-test-image
    dir: .
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --target build --tag category:test .

  - id: run-tests
    dir: .
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker container run category:test mvn test

  - id: build-app
    dir: .
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --tag ${_REGION}-docker.pkg.dev/$PROJECT_ID/ajustadoati-repo/category:$COMMIT_SHA .

  - id: kubeval
    dir: .
    name: cloudnatived/helm-cloudbuilder
    entrypoint: sh
    args:
      - -c
      - |
        helm template ./category/ | kubeval

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/ajustadoati-repo/category:$COMMIT_SHA
